version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: auction-db
    environment:
      POSTGRES_DB: auction_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Automatically initialize the database schema
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    container_name: auction-app
    ports:
      - "1234:1234"
    environment:
      - APP_DB_URL=r2dbc:postgresql://db:5432/auction_shop
      - APP_DB_USERNAME=postgres
      - APP_DB_PASSWORD=your_password_here
      - SECURITY_JWT_SECRET=cmFwaWRseWJyb2tlbG93YXdhcmVzaW1wbGVzdGZhbGxza2lsbHRvbW9ycm93b25ldHI=
    depends_on:
      - db

volumes:
  postgres_data:
