server:
  port: 1234

spring:
  r2dbc:
    url: ${APP_DB_URL:r2dbc:postgresql://localhost:5432/auction_shop}
    username: ${APP_DB_USERNAME:postgres}
    password: ${APP_DB_PASSWORD:GIANG2007}

security:
  jwt:
    issuer: auction-shop
    expiration-ms: 86400000
    secret: cmFwaWRseWJyb2tlbG93YXdhcmVzaW1wbGVzdGZhbGxza2lsbHRvbW9ycm93b25ldHI=
