server:
  port: 1234

spring:
  r2dbc:
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
  lifecycle:
    timeout-per-shutdown-phase: 30s

security:
  jwt:
    issuer: auction-shop
    expiration-ms: 86400000
    secret: ${SECURITY_JWT_SECRET}

cache:
  default-expiration-seconds: 900
  cleanup-interval-seconds: 300
