server:
  port: 1234

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  lifecycle:
    timeout-per-shutdown-phase: 30s

security:
  jwt:
    issuer: auction-shop
    expiration-ms: 86400000
    secret: ${JWT_SECRET}
